### ISSUE TITLE
Gargoyle main site 502 error

### ISSUE THREAD

**Issue by lantis1008** [ericpaulbishop/gargoyle#578] opened 2016-11-25 23:23 UTC
The main site is giving a 502 Bad Gateway currently. 
Also are you interested in adding any CAPTCHA services to the sign up process? Spam has hit an all time high. 20-30 posts per day.

**Comment by ericpaulbishop** [comment] 2016-11-26 00:01
Thanks for the heads-up on the 502 error -- it should be fixed now. It was caused by running out of disk space. I purged some old log files for the web server which were piling up, which is why it ran out of space in the first place.

At one point I used the default phpbb captcha, but it did almost nothing to prevent spam. The spammers clearly had figured out a way to get past the standard captchas for phpbb and had automated it. The question I now have to prove you're human is easy to hack for one specific site, but not for phpbb boards in general since it's different than the standard captcha. For a while that was limiting spam... but I guess the spammers have caught up.

Is there a specific captcha you would suggest to limit the spammers?

**Closed by ericpaulbishop** 2016-11-26 00:01 UTC

**Comment by lantis1008** [comment] 2016-11-26 00:15
3 possible solutions:
- Sortables CAPTCHA plugin, seems to get good reports. There's a live demo I found on Google. 
- blocking UTC-12 registration. I believe the theory is that you make that the default Timezone, and make it an invalid option to register with. UTC-12 is an uninhabited Timezone anyway ;)
- custom field in the registration with a default value selected that is invalid. 
Like a list of 5 numbers, please choose the middle one. Set the default selection to the first number and it fails by default.

**Comment by tapper82** [comment] 2016-12-21 12:12
Hi I don't know what is the rite approach to stopping the spam but it is getting a rite pane to keep on top of! I am logging in about 3-4 times a day and every time there is 5-6 spam posts i have to remove. I start a new job after Xmas so won't have the time to be on the forum so much. Will upgrading to PHPB 3.0.13 help?
https://www.phpbb.com/support/documents.php?mode=changelog
I don't think updating to the latest PHPB 3.1 would be a good thing as it mite mess up the layout for my screenreader.

**Comment by ericpaulbishop** [comment] 2016-12-21 16:37
I think updating to 3.1 may be the best way to go, as there are more plugins available for the newer version of PHPBB that may help with the spam problem. I will try to get to this upgrade within the next week, though I'm not sure if I'll get to it before Christmas -- I expect to have more time available after Christmas than before.

**Comment by ispyisail** [comment] 2016-12-21 17:56
+1 to any improvement really

**Comment by tapper82** [comment] 2016-12-28 18:36
Hi eric sorry i did not see your edit. How do i find other PHPBB 3.1  forums? I did a quick Google and did not find any.

**Comment by lantis1008** [comment] 2016-12-28 21:21
http://try-phpbb.com/31x/

phpbb intentionally does not list its version to users for security.

**Comment by tapper82** [comment] 2016-12-28 21:39
Thanks lantis  :) Just had a look at that link and it works OK.

**Comment by ektus** [comment] 2016-12-29 16:31
I'm looking forward to any SPAM protection action. I did post on https://www.gargoyle-router.com/phpbb/viewtopic.php?f=5&t=10549 just a day ago without being aware of the discussion here, and hope the new PHPbb an Captcha versions prove effective :-)

Regards
Ektus.

**Comment by ericpaulbishop** [comment] 2017-01-02 18:49
Forum is now upgraded, and new "Sortables Captcha" plugin is installed. We'll see how this works at limiting the spam.
