### ISSUE TITLE
QoS rules disappear if you try save with two browser windows in QoS page

### ISSUE THREAD

**Issue by thiagokokada** [ericpaulbishop/gargoyle#535] opened 2016-05-06 15:21 UTC
I think this is a known bug (I saw some reports in forum), however since I didn't saw a report here I think it is nice to put it, at least to documment that it exist.

Basically, all QoS rules will disappear if you try to save them when another browser window/tab is already in QoS rules page too. Note that it needs to be the same one as you're editting (Download/Upload).

After triggering this bug, there is no way to edit QoS rules until a reset or backup restoration.

**Comment by lantis1008** [comment] 2016-05-06 20:54
This is expected behaviour. The interface isn't designed to be opened twice.

**Comment by ericpaulbishop** [comment] 2016-05-06 21:07
It would be wrong to call this "expected behavior." This is more along the lines of "low priority bug" because this really shouldn't be a common occurrence given the interface is not typically used this way. If you can figure out what causes this and fix it, it would be good, but I'm not quite sure why this happens, on top of which, it seems to be intermitent (in my experience).

**Comment by lantis1008** [comment] 2016-05-06 21:10
I believe @stopspazzing said this behaviour could be corrected by moving to html 5 and using "sessions" to store the temp data. These sessions can be locked to a window/tab, or made global. 

This is my recollection.

**Comment by ericpaulbishop** [comment] 2016-05-06 21:21
Yes and no. That's definitely a good approach to limiting session data to a single tab. The problem is I need to know what data is conflicting to cause this problem. I've never been able to figure out what/where the conflict is to eliminate the bug. Again, my observation is that it's intermittent (as with many bugs that get triggered by timing conflicts) which makes debugging harder.

**Comment by jaf0** [comment] 2016-05-06 21:22
I saw a similar issue with quotas when I edited on a different computer 
and had the UI open on mine.

**Comment by m45t3r** [comment] 2016-05-06 22:57
@ericpaulbishop @lantis1008 I am bite by this bug all the time since I use too many tabs. Sometimes I am changing QoS settings, forgot that I already opened one tab on QoS page, open another one, edit, save and lose all my settings.

**Closed** 2019-04-24 23:39 UTC
