### ISSUE TITLE
translation for custom bandwith monitor in zh_cn

### ISSUE THREAD

**Issue by crackself** [ericpaulbishop/gargoyle#705] opened 2017-12-24 01:30 UTC
some translate fix fo zh_cn.
(I can't make a pull request with a single commit,so only as  pathc here)

[fix_translate_in_zh-cn.txt](https://github.com/ericpaulbishop/gargoyle/files/1584549/fix_translate_in_zh-cn.txt)

**Comment by crackself** [comment] 2017-12-24 01:32
[fix_translate_in_zh-cn.txt](https://github.com/ericpaulbishop/gargoyle/files/1584548/fix_translate_in_zh-cn.txt)

**Comment by lantis1008** [comment] 2017-12-24 01:32
I’ll do this for you in the next few days. 
Thanks.

**Comment by crackself** [comment] 2017-12-24 01:39
![interval](https://user-images.githubusercontent.com/16448332/34323631-90314120-e88d-11e7-9dec-3f2ce090ffcd.png)
"moniter interval" selection default as month,not allow to change.

**Comment by lantis1008** [comment] 2017-12-24 01:40
That is intentional and not a bug.

**Comment by crackself** [comment] 2017-12-24 01:43
@lantis1008 understand.

**Comment by d3fz** [comment] 2017-12-24 15:12
The request has been addressed in the mentioned PR. Now waiting for approval & merge.

**Closed** 2017-12-30 15:53 UTC
